import { Slide01ReplayFixture } from "./slide01.types";

export const SLIDE01_GESTURE_TRACE_FIXTURES: Slide01ReplayFixture[] = [
  {
    id: "slide01-sealed-0001",
    description: "Sealed deterministic trace slide01-sealed-0001.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 108, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 148, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 364, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 566, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 324, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 566, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 324, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 324, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0002",
    description: "Sealed deterministic trace slide01-sealed-0002.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 92, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 160, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 348, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 578, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 308, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 578, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 308, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 308, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0003",
    description: "Sealed deterministic trace slide01-sealed-0003.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 104, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 144, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 360, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 562, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 320, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 562, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 320, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 320, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0004",
    description: "Sealed deterministic trace slide01-sealed-0004.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 88, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 156, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 344, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 574, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 332, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 574, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 332, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 332, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0005",
    description: "Sealed deterministic trace slide01-sealed-0005.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 100, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 140, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 356, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 586, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 316, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 586, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 316, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 316, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0006",
    description: "Sealed deterministic trace slide01-sealed-0006.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 84, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 152, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 368, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 570, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 328, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 570, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 328, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 328, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0007",
    description: "Sealed deterministic trace slide01-sealed-0007.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 96, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 164, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 352, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 582, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 312, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 582, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 312, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 312, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0008",
    description: "Sealed deterministic trace slide01-sealed-0008.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 108, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 148, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 364, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 566, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 324, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 566, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 324, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 324, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0009",
    description: "Sealed deterministic trace slide01-sealed-0009.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 92, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 160, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 348, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 578, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 308, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 578, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 308, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 308, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0010",
    description: "Sealed deterministic trace slide01-sealed-0010.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 104, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 144, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 360, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 562, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 320, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 562, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 320, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 320, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0011",
    description: "Sealed deterministic trace slide01-sealed-0011.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 88, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 156, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 344, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 574, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 332, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 574, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 332, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 332, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0012",
    description: "Sealed deterministic trace slide01-sealed-0012.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 100, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 140, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 356, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 586, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 316, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 586, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 316, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 316, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0013",
    description: "Sealed deterministic trace slide01-sealed-0013.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 84, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 152, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 368, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 570, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 328, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 570, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 328, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 328, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0014",
    description: "Sealed deterministic trace slide01-sealed-0014.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 96, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 164, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 352, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 582, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 312, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 582, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 312, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 312, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0015",
    description: "Sealed deterministic trace slide01-sealed-0015.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 108, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 148, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 364, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 566, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 324, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 566, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 324, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 324, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0016",
    description: "Sealed deterministic trace slide01-sealed-0016.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 92, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 160, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 348, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 578, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 308, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 578, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 308, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 308, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0017",
    description: "Sealed deterministic trace slide01-sealed-0017.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 104, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 144, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 360, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 562, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 320, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 562, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 320, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 320, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0018",
    description: "Sealed deterministic trace slide01-sealed-0018.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 88, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 156, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 344, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 574, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 332, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 574, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 332, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 332, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0019",
    description: "Sealed deterministic trace slide01-sealed-0019.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 100, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 140, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 356, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 586, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 316, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 586, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 316, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 316, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0020",
    description: "Sealed deterministic trace slide01-sealed-0020.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 84, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 152, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 368, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 570, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 328, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 570, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 328, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 328, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0021",
    description: "Sealed deterministic trace slide01-sealed-0021.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 96, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 164, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 352, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 582, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 312, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 582, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 312, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 312, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0022",
    description: "Sealed deterministic trace slide01-sealed-0022.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 108, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 148, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 364, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 566, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 324, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 566, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 324, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 324, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0023",
    description: "Sealed deterministic trace slide01-sealed-0023.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 92, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 160, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 348, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 578, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 308, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 578, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 308, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 308, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0024",
    description: "Sealed deterministic trace slide01-sealed-0024.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 104, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 144, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 360, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 562, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 320, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 562, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 320, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 320, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0025",
    description: "Sealed deterministic trace slide01-sealed-0025.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 88, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 156, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 344, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 574, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 332, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 574, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 332, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 332, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0026",
    description: "Sealed deterministic trace slide01-sealed-0026.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 100, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 140, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 356, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 586, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 316, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 586, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 316, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 316, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0027",
    description: "Sealed deterministic trace slide01-sealed-0027.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 84, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 152, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 368, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 570, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 328, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 570, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 328, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 328, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0028",
    description: "Sealed deterministic trace slide01-sealed-0028.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 96, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 164, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 352, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 582, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 312, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 582, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 312, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 312, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0029",
    description: "Sealed deterministic trace slide01-sealed-0029.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 108, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 148, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 364, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 566, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 324, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 566, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 324, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 324, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0030",
    description: "Sealed deterministic trace slide01-sealed-0030.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 92, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 160, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 348, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 578, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 308, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 578, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 308, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 308, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0031",
    description: "Sealed deterministic trace slide01-sealed-0031.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 104, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 144, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 360, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 562, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 320, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 562, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 320, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 320, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-sealed-0032",
    description: "Sealed deterministic trace slide01-sealed-0032.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 88, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 156, y: 124, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 344, y: 156, timestampMs: 46 },
      { type: "pointer_move", pointerId: 1, x: 574, y: 184, timestampMs: 68 },
      { type: "pointer_move", pointerId: 1, x: 332, y: 326, timestampMs: 94 },
      { type: "pointer_move", pointerId: 1, x: 574, y: 184, timestampMs: 126 },
      { type: "pointer_move", pointerId: 1, x: 332, y: 326, timestampMs: 152 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 272 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 392 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 512 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 632 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 752 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 872 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 992 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1112 },
      { type: "pointer_up", pointerId: 1, x: 332, y: 326, timestampMs: 1138 },
    ],
    expected: {
      stage: "Sealed",
      sealStatus: "sealed",
      completed: true,
      engagedFaultCount: 4,
      totalProgressMin: 1.00,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
        "gesture:slide01-release:completed",
        "state:slide01-sealed:set",
        "evidence:slide01-primary:satisfied",
      ],
    },
  },
  {
    id: "slide01-ready-0001",
    description: "Release-ready deterministic trace slide01-ready-0001.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 98, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 166, y: 126, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 348, y: 158, timestampMs: 48 },
      { type: "pointer_move", pointerId: 1, x: 580, y: 182, timestampMs: 74 },
      { type: "pointer_move", pointerId: 1, x: 314, y: 330, timestampMs: 98 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 220 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 340 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 460 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 580 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 700 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 820 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 940 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1060 },
    ],
    expected: {
      stage: "ReleaseReady",
      sealStatus: "evidence-accepted",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.85,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
      ],
    },
  },
  {
    id: "slide01-ready-0002",
    description: "Release-ready deterministic trace slide01-ready-0002.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 110, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 150, y: 126, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 360, y: 158, timestampMs: 48 },
      { type: "pointer_move", pointerId: 1, x: 564, y: 182, timestampMs: 74 },
      { type: "pointer_move", pointerId: 1, x: 326, y: 330, timestampMs: 98 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 220 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 340 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 460 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 580 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 700 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 820 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 940 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1060 },
    ],
    expected: {
      stage: "ReleaseReady",
      sealStatus: "evidence-accepted",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.85,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
      ],
    },
  },
  {
    id: "slide01-ready-0003",
    description: "Release-ready deterministic trace slide01-ready-0003.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 94, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 162, y: 126, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 344, y: 158, timestampMs: 48 },
      { type: "pointer_move", pointerId: 1, x: 576, y: 182, timestampMs: 74 },
      { type: "pointer_move", pointerId: 1, x: 310, y: 330, timestampMs: 98 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 220 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 340 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 460 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 580 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 700 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 820 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 940 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1060 },
    ],
    expected: {
      stage: "ReleaseReady",
      sealStatus: "evidence-accepted",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.85,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
      ],
    },
  },
  {
    id: "slide01-ready-0004",
    description: "Release-ready deterministic trace slide01-ready-0004.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 106, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 146, y: 126, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 356, y: 158, timestampMs: 48 },
      { type: "pointer_move", pointerId: 1, x: 560, y: 182, timestampMs: 74 },
      { type: "pointer_move", pointerId: 1, x: 322, y: 330, timestampMs: 98 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 220 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 340 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 460 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 580 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 700 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 820 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 940 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1060 },
    ],
    expected: {
      stage: "ReleaseReady",
      sealStatus: "evidence-accepted",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.85,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
      ],
    },
  },
  {
    id: "slide01-ready-0005",
    description: "Release-ready deterministic trace slide01-ready-0005.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 90, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 158, y: 126, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 340, y: 158, timestampMs: 48 },
      { type: "pointer_move", pointerId: 1, x: 572, y: 182, timestampMs: 74 },
      { type: "pointer_move", pointerId: 1, x: 334, y: 330, timestampMs: 98 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 220 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 340 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 460 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 580 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 700 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 820 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 940 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1060 },
    ],
    expected: {
      stage: "ReleaseReady",
      sealStatus: "evidence-accepted",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.85,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
      ],
    },
  },
  {
    id: "slide01-ready-0006",
    description: "Release-ready deterministic trace slide01-ready-0006.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 102, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 142, y: 126, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 352, y: 158, timestampMs: 48 },
      { type: "pointer_move", pointerId: 1, x: 584, y: 182, timestampMs: 74 },
      { type: "pointer_move", pointerId: 1, x: 318, y: 330, timestampMs: 98 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 220 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 340 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 460 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 580 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 700 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 820 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 940 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1060 },
    ],
    expected: {
      stage: "ReleaseReady",
      sealStatus: "evidence-accepted",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.85,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
      ],
    },
  },
  {
    id: "slide01-ready-0007",
    description: "Release-ready deterministic trace slide01-ready-0007.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 86, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 154, y: 126, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 364, y: 158, timestampMs: 48 },
      { type: "pointer_move", pointerId: 1, x: 568, y: 182, timestampMs: 74 },
      { type: "pointer_move", pointerId: 1, x: 330, y: 330, timestampMs: 98 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 220 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 340 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 460 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 580 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 700 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 820 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 940 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1060 },
    ],
    expected: {
      stage: "ReleaseReady",
      sealStatus: "evidence-accepted",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.85,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
      ],
    },
  },
  {
    id: "slide01-ready-0008",
    description: "Release-ready deterministic trace slide01-ready-0008.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 98, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 166, y: 126, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 348, y: 158, timestampMs: 48 },
      { type: "pointer_move", pointerId: 1, x: 580, y: 182, timestampMs: 74 },
      { type: "pointer_move", pointerId: 1, x: 314, y: 330, timestampMs: 98 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 220 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 340 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 460 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 580 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 700 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 820 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 940 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1060 },
    ],
    expected: {
      stage: "ReleaseReady",
      sealStatus: "evidence-accepted",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.85,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
      ],
    },
  },
  {
    id: "slide01-ready-0009",
    description: "Release-ready deterministic trace slide01-ready-0009.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 110, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 150, y: 126, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 360, y: 158, timestampMs: 48 },
      { type: "pointer_move", pointerId: 1, x: 564, y: 182, timestampMs: 74 },
      { type: "pointer_move", pointerId: 1, x: 326, y: 330, timestampMs: 98 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 220 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 340 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 460 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 580 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 700 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 820 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 940 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1060 },
    ],
    expected: {
      stage: "ReleaseReady",
      sealStatus: "evidence-accepted",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.85,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
      ],
    },
  },
  {
    id: "slide01-ready-0010",
    description: "Release-ready deterministic trace slide01-ready-0010.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 94, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 162, y: 126, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 344, y: 158, timestampMs: 48 },
      { type: "pointer_move", pointerId: 1, x: 576, y: 182, timestampMs: 74 },
      { type: "pointer_move", pointerId: 1, x: 310, y: 330, timestampMs: 98 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 220 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 340 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 460 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 580 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 700 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 820 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 940 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1060 },
    ],
    expected: {
      stage: "ReleaseReady",
      sealStatus: "evidence-accepted",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.85,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
      ],
    },
  },
  {
    id: "slide01-ready-0011",
    description: "Release-ready deterministic trace slide01-ready-0011.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 106, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 146, y: 126, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 356, y: 158, timestampMs: 48 },
      { type: "pointer_move", pointerId: 1, x: 560, y: 182, timestampMs: 74 },
      { type: "pointer_move", pointerId: 1, x: 322, y: 330, timestampMs: 98 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 220 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 340 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 460 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 580 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 700 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 820 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 940 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1060 },
    ],
    expected: {
      stage: "ReleaseReady",
      sealStatus: "evidence-accepted",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.85,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
      ],
    },
  },
  {
    id: "slide01-ready-0012",
    description: "Release-ready deterministic trace slide01-ready-0012.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 90, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 158, y: 126, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 340, y: 158, timestampMs: 48 },
      { type: "pointer_move", pointerId: 1, x: 572, y: 182, timestampMs: 74 },
      { type: "pointer_move", pointerId: 1, x: 334, y: 330, timestampMs: 98 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 220 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 340 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 460 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 580 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 700 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 820 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 940 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1060 },
    ],
    expected: {
      stage: "ReleaseReady",
      sealStatus: "evidence-accepted",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.85,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
      ],
    },
  },
  {
    id: "slide01-ready-0013",
    description: "Release-ready deterministic trace slide01-ready-0013.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 102, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 142, y: 126, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 352, y: 158, timestampMs: 48 },
      { type: "pointer_move", pointerId: 1, x: 584, y: 182, timestampMs: 74 },
      { type: "pointer_move", pointerId: 1, x: 318, y: 330, timestampMs: 98 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 220 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 340 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 460 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 580 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 700 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 820 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 940 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1060 },
    ],
    expected: {
      stage: "ReleaseReady",
      sealStatus: "evidence-accepted",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.85,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
      ],
    },
  },
  {
    id: "slide01-ready-0014",
    description: "Release-ready deterministic trace slide01-ready-0014.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 86, y: 120, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 154, y: 126, timestampMs: 24 },
      { type: "pointer_move", pointerId: 1, x: 364, y: 158, timestampMs: 48 },
      { type: "pointer_move", pointerId: 1, x: 568, y: 182, timestampMs: 74 },
      { type: "pointer_move", pointerId: 1, x: 330, y: 330, timestampMs: 98 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 220 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 340 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 460 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 580 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 700 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 820 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 940 },
      { type: "hold_tick", deltaMs: 120, timestampMs: 1060 },
    ],
    expected: {
      stage: "ReleaseReady",
      sealStatus: "evidence-accepted",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.85,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
        "gesture:slide01-hold:completed",
      ],
    },
  },
  {
    id: "slide01-drag-0001",
    description: "Drag-ready deterministic trace slide01-drag-0001.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 82, y: 118, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 154, y: 124, timestampMs: 28 },
      { type: "pointer_move", pointerId: 1, x: 362, y: 156, timestampMs: 52 },
      { type: "pointer_move", pointerId: 1, x: 570, y: 184, timestampMs: 76 },
      { type: "pointer_move", pointerId: 1, x: 334, y: 332, timestampMs: 100 },
      { type: "pointer_up", pointerId: 1, x: 334, y: 332, timestampMs: 118 },
    ],
    expected: {
      stage: "DragReady",
      sealStatus: "responsibility-pending",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.45,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
      ],
    },
  },
  {
    id: "slide01-drag-0002",
    description: "Drag-ready deterministic trace slide01-drag-0002.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 94, y: 118, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 166, y: 124, timestampMs: 28 },
      { type: "pointer_move", pointerId: 1, x: 346, y: 156, timestampMs: 52 },
      { type: "pointer_move", pointerId: 1, x: 582, y: 184, timestampMs: 76 },
      { type: "pointer_move", pointerId: 1, x: 318, y: 332, timestampMs: 100 },
      { type: "pointer_up", pointerId: 1, x: 318, y: 332, timestampMs: 118 },
    ],
    expected: {
      stage: "DragReady",
      sealStatus: "responsibility-pending",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.45,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
      ],
    },
  },
  {
    id: "slide01-drag-0003",
    description: "Drag-ready deterministic trace slide01-drag-0003.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 106, y: 118, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 150, y: 124, timestampMs: 28 },
      { type: "pointer_move", pointerId: 1, x: 358, y: 156, timestampMs: 52 },
      { type: "pointer_move", pointerId: 1, x: 566, y: 184, timestampMs: 76 },
      { type: "pointer_move", pointerId: 1, x: 330, y: 332, timestampMs: 100 },
      { type: "pointer_up", pointerId: 1, x: 330, y: 332, timestampMs: 118 },
    ],
    expected: {
      stage: "DragReady",
      sealStatus: "responsibility-pending",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.45,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
      ],
    },
  },
  {
    id: "slide01-drag-0004",
    description: "Drag-ready deterministic trace slide01-drag-0004.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 90, y: 118, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 162, y: 124, timestampMs: 28 },
      { type: "pointer_move", pointerId: 1, x: 342, y: 156, timestampMs: 52 },
      { type: "pointer_move", pointerId: 1, x: 578, y: 184, timestampMs: 76 },
      { type: "pointer_move", pointerId: 1, x: 314, y: 332, timestampMs: 100 },
      { type: "pointer_up", pointerId: 1, x: 314, y: 332, timestampMs: 118 },
    ],
    expected: {
      stage: "DragReady",
      sealStatus: "responsibility-pending",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.45,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
      ],
    },
  },
  {
    id: "slide01-drag-0005",
    description: "Drag-ready deterministic trace slide01-drag-0005.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 102, y: 118, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 146, y: 124, timestampMs: 28 },
      { type: "pointer_move", pointerId: 1, x: 354, y: 156, timestampMs: 52 },
      { type: "pointer_move", pointerId: 1, x: 562, y: 184, timestampMs: 76 },
      { type: "pointer_move", pointerId: 1, x: 326, y: 332, timestampMs: 100 },
      { type: "pointer_up", pointerId: 1, x: 326, y: 332, timestampMs: 118 },
    ],
    expected: {
      stage: "DragReady",
      sealStatus: "responsibility-pending",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.45,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
      ],
    },
  },
  {
    id: "slide01-drag-0006",
    description: "Drag-ready deterministic trace slide01-drag-0006.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 86, y: 118, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 158, y: 124, timestampMs: 28 },
      { type: "pointer_move", pointerId: 1, x: 338, y: 156, timestampMs: 52 },
      { type: "pointer_move", pointerId: 1, x: 574, y: 184, timestampMs: 76 },
      { type: "pointer_move", pointerId: 1, x: 338, y: 332, timestampMs: 100 },
      { type: "pointer_up", pointerId: 1, x: 338, y: 332, timestampMs: 118 },
    ],
    expected: {
      stage: "DragReady",
      sealStatus: "responsibility-pending",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.45,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
      ],
    },
  },
  {
    id: "slide01-drag-0007",
    description: "Drag-ready deterministic trace slide01-drag-0007.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 98, y: 118, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 142, y: 124, timestampMs: 28 },
      { type: "pointer_move", pointerId: 1, x: 350, y: 156, timestampMs: 52 },
      { type: "pointer_move", pointerId: 1, x: 586, y: 184, timestampMs: 76 },
      { type: "pointer_move", pointerId: 1, x: 322, y: 332, timestampMs: 100 },
      { type: "pointer_up", pointerId: 1, x: 322, y: 332, timestampMs: 118 },
    ],
    expected: {
      stage: "DragReady",
      sealStatus: "responsibility-pending",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.45,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
      ],
    },
  },
  {
    id: "slide01-drag-0008",
    description: "Drag-ready deterministic trace slide01-drag-0008.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 82, y: 118, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 154, y: 124, timestampMs: 28 },
      { type: "pointer_move", pointerId: 1, x: 362, y: 156, timestampMs: 52 },
      { type: "pointer_move", pointerId: 1, x: 570, y: 184, timestampMs: 76 },
      { type: "pointer_move", pointerId: 1, x: 334, y: 332, timestampMs: 100 },
      { type: "pointer_up", pointerId: 1, x: 334, y: 332, timestampMs: 118 },
    ],
    expected: {
      stage: "DragReady",
      sealStatus: "responsibility-pending",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.45,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
      ],
    },
  },
  {
    id: "slide01-drag-0009",
    description: "Drag-ready deterministic trace slide01-drag-0009.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 94, y: 118, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 166, y: 124, timestampMs: 28 },
      { type: "pointer_move", pointerId: 1, x: 346, y: 156, timestampMs: 52 },
      { type: "pointer_move", pointerId: 1, x: 582, y: 184, timestampMs: 76 },
      { type: "pointer_move", pointerId: 1, x: 318, y: 332, timestampMs: 100 },
      { type: "pointer_up", pointerId: 1, x: 318, y: 332, timestampMs: 118 },
    ],
    expected: {
      stage: "DragReady",
      sealStatus: "responsibility-pending",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.45,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
      ],
    },
  },
  {
    id: "slide01-drag-0010",
    description: "Drag-ready deterministic trace slide01-drag-0010.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 106, y: 118, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 150, y: 124, timestampMs: 28 },
      { type: "pointer_move", pointerId: 1, x: 358, y: 156, timestampMs: 52 },
      { type: "pointer_move", pointerId: 1, x: 566, y: 184, timestampMs: 76 },
      { type: "pointer_move", pointerId: 1, x: 330, y: 332, timestampMs: 100 },
      { type: "pointer_up", pointerId: 1, x: 330, y: 332, timestampMs: 118 },
    ],
    expected: {
      stage: "DragReady",
      sealStatus: "responsibility-pending",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.45,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
      ],
    },
  },
  {
    id: "slide01-drag-0011",
    description: "Drag-ready deterministic trace slide01-drag-0011.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 90, y: 118, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 162, y: 124, timestampMs: 28 },
      { type: "pointer_move", pointerId: 1, x: 342, y: 156, timestampMs: 52 },
      { type: "pointer_move", pointerId: 1, x: 578, y: 184, timestampMs: 76 },
      { type: "pointer_move", pointerId: 1, x: 314, y: 332, timestampMs: 100 },
      { type: "pointer_up", pointerId: 1, x: 314, y: 332, timestampMs: 118 },
    ],
    expected: {
      stage: "DragReady",
      sealStatus: "responsibility-pending",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.45,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
      ],
    },
  },
  {
    id: "slide01-drag-0012",
    description: "Drag-ready deterministic trace slide01-drag-0012.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 102, y: 118, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 146, y: 124, timestampMs: 28 },
      { type: "pointer_move", pointerId: 1, x: 354, y: 156, timestampMs: 52 },
      { type: "pointer_move", pointerId: 1, x: 562, y: 184, timestampMs: 76 },
      { type: "pointer_move", pointerId: 1, x: 326, y: 332, timestampMs: 100 },
      { type: "pointer_up", pointerId: 1, x: 326, y: 332, timestampMs: 118 },
    ],
    expected: {
      stage: "DragReady",
      sealStatus: "responsibility-pending",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.45,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
      ],
    },
  },
  {
    id: "slide01-drag-0013",
    description: "Drag-ready deterministic trace slide01-drag-0013.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 86, y: 118, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 158, y: 124, timestampMs: 28 },
      { type: "pointer_move", pointerId: 1, x: 338, y: 156, timestampMs: 52 },
      { type: "pointer_move", pointerId: 1, x: 574, y: 184, timestampMs: 76 },
      { type: "pointer_move", pointerId: 1, x: 338, y: 332, timestampMs: 100 },
      { type: "pointer_up", pointerId: 1, x: 338, y: 332, timestampMs: 118 },
    ],
    expected: {
      stage: "DragReady",
      sealStatus: "responsibility-pending",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.45,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
      ],
    },
  },
  {
    id: "slide01-drag-0014",
    description: "Drag-ready deterministic trace slide01-drag-0014.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 98, y: 118, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 142, y: 124, timestampMs: 28 },
      { type: "pointer_move", pointerId: 1, x: 350, y: 156, timestampMs: 52 },
      { type: "pointer_move", pointerId: 1, x: 586, y: 184, timestampMs: 76 },
      { type: "pointer_move", pointerId: 1, x: 322, y: 332, timestampMs: 100 },
      { type: "pointer_up", pointerId: 1, x: 322, y: 332, timestampMs: 118 },
    ],
    expected: {
      stage: "DragReady",
      sealStatus: "responsibility-pending",
      completed: false,
      engagedFaultCount: 4,
      totalProgressMin: 0.45,
      requiredEventNames: [
        "slide:01:entered",
        "gesture:slide01-drag:completed",
      ],
    },
  },
  {
    id: "slide01-intent-0001",
    description: "Intent deterministic trace slide01-intent-0001.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 96, y: 116, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 144, y: 124, timestampMs: 32 },
      { type: "pointer_up", pointerId: 1, x: 144, y: 124, timestampMs: 54 },
    ],
    expected: {
      stage: "Dragging",
      sealStatus: "intent-registered",
      completed: false,
      engagedFaultCount: 1,
      totalProgressMin: 0.12,
      requiredEventNames: [
        "slide:01:entered",
      ],
    },
  },
  {
    id: "slide01-intent-0002",
    description: "Intent deterministic trace slide01-intent-0002.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 80, y: 116, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 156, y: 124, timestampMs: 32 },
      { type: "pointer_up", pointerId: 1, x: 156, y: 124, timestampMs: 54 },
    ],
    expected: {
      stage: "Dragging",
      sealStatus: "intent-registered",
      completed: false,
      engagedFaultCount: 1,
      totalProgressMin: 0.12,
      requiredEventNames: [
        "slide:01:entered",
      ],
    },
  },
  {
    id: "slide01-intent-0003",
    description: "Intent deterministic trace slide01-intent-0003.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 92, y: 116, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 168, y: 124, timestampMs: 32 },
      { type: "pointer_up", pointerId: 1, x: 168, y: 124, timestampMs: 54 },
    ],
    expected: {
      stage: "Dragging",
      sealStatus: "intent-registered",
      completed: false,
      engagedFaultCount: 1,
      totalProgressMin: 0.12,
      requiredEventNames: [
        "slide:01:entered",
      ],
    },
  },
  {
    id: "slide01-intent-0004",
    description: "Intent deterministic trace slide01-intent-0004.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 104, y: 116, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 152, y: 124, timestampMs: 32 },
      { type: "pointer_up", pointerId: 1, x: 152, y: 124, timestampMs: 54 },
    ],
    expected: {
      stage: "Dragging",
      sealStatus: "intent-registered",
      completed: false,
      engagedFaultCount: 1,
      totalProgressMin: 0.12,
      requiredEventNames: [
        "slide:01:entered",
      ],
    },
  },
  {
    id: "slide01-intent-0005",
    description: "Intent deterministic trace slide01-intent-0005.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 88, y: 116, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 164, y: 124, timestampMs: 32 },
      { type: "pointer_up", pointerId: 1, x: 164, y: 124, timestampMs: 54 },
    ],
    expected: {
      stage: "Dragging",
      sealStatus: "intent-registered",
      completed: false,
      engagedFaultCount: 1,
      totalProgressMin: 0.12,
      requiredEventNames: [
        "slide:01:entered",
      ],
    },
  },
  {
    id: "slide01-intent-0006",
    description: "Intent deterministic trace slide01-intent-0006.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 100, y: 116, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 148, y: 124, timestampMs: 32 },
      { type: "pointer_up", pointerId: 1, x: 148, y: 124, timestampMs: 54 },
    ],
    expected: {
      stage: "Dragging",
      sealStatus: "intent-registered",
      completed: false,
      engagedFaultCount: 1,
      totalProgressMin: 0.12,
      requiredEventNames: [
        "slide:01:entered",
      ],
    },
  },
  {
    id: "slide01-intent-0007",
    description: "Intent deterministic trace slide01-intent-0007.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 84, y: 116, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 160, y: 124, timestampMs: 32 },
      { type: "pointer_up", pointerId: 1, x: 160, y: 124, timestampMs: 54 },
    ],
    expected: {
      stage: "Dragging",
      sealStatus: "intent-registered",
      completed: false,
      engagedFaultCount: 1,
      totalProgressMin: 0.12,
      requiredEventNames: [
        "slide:01:entered",
      ],
    },
  },
  {
    id: "slide01-intent-0008",
    description: "Intent deterministic trace slide01-intent-0008.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 96, y: 116, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 144, y: 124, timestampMs: 32 },
      { type: "pointer_up", pointerId: 1, x: 144, y: 124, timestampMs: 54 },
    ],
    expected: {
      stage: "Dragging",
      sealStatus: "intent-registered",
      completed: false,
      engagedFaultCount: 1,
      totalProgressMin: 0.12,
      requiredEventNames: [
        "slide:01:entered",
      ],
    },
  },
  {
    id: "slide01-intent-0009",
    description: "Intent deterministic trace slide01-intent-0009.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 80, y: 116, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 156, y: 124, timestampMs: 32 },
      { type: "pointer_up", pointerId: 1, x: 156, y: 124, timestampMs: 54 },
    ],
    expected: {
      stage: "Dragging",
      sealStatus: "intent-registered",
      completed: false,
      engagedFaultCount: 1,
      totalProgressMin: 0.12,
      requiredEventNames: [
        "slide:01:entered",
      ],
    },
  },
  {
    id: "slide01-intent-0010",
    description: "Intent deterministic trace slide01-intent-0010.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 92, y: 116, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 168, y: 124, timestampMs: 32 },
      { type: "pointer_up", pointerId: 1, x: 168, y: 124, timestampMs: 54 },
    ],
    expected: {
      stage: "Dragging",
      sealStatus: "intent-registered",
      completed: false,
      engagedFaultCount: 1,
      totalProgressMin: 0.12,
      requiredEventNames: [
        "slide:01:entered",
      ],
    },
  },
  {
    id: "slide01-intent-0011",
    description: "Intent deterministic trace slide01-intent-0011.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 104, y: 116, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 152, y: 124, timestampMs: 32 },
      { type: "pointer_up", pointerId: 1, x: 152, y: 124, timestampMs: 54 },
    ],
    expected: {
      stage: "Dragging",
      sealStatus: "intent-registered",
      completed: false,
      engagedFaultCount: 1,
      totalProgressMin: 0.12,
      requiredEventNames: [
        "slide:01:entered",
      ],
    },
  },
  {
    id: "slide01-intent-0012",
    description: "Intent deterministic trace slide01-intent-0012.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 88, y: 116, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 164, y: 124, timestampMs: 32 },
      { type: "pointer_up", pointerId: 1, x: 164, y: 124, timestampMs: 54 },
    ],
    expected: {
      stage: "Dragging",
      sealStatus: "intent-registered",
      completed: false,
      engagedFaultCount: 1,
      totalProgressMin: 0.12,
      requiredEventNames: [
        "slide:01:entered",
      ],
    },
  },
  {
    id: "slide01-intent-0013",
    description: "Intent deterministic trace slide01-intent-0013.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 100, y: 116, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 148, y: 124, timestampMs: 32 },
      { type: "pointer_up", pointerId: 1, x: 148, y: 124, timestampMs: 54 },
    ],
    expected: {
      stage: "Dragging",
      sealStatus: "intent-registered",
      completed: false,
      engagedFaultCount: 1,
      totalProgressMin: 0.12,
      requiredEventNames: [
        "slide:01:entered",
      ],
    },
  },
  {
    id: "slide01-intent-0014",
    description: "Intent deterministic trace slide01-intent-0014.",
    trace: [
      { type: "entered", timestampMs: 0 },
      { type: "pointer_down", pointerId: 1, x: 84, y: 116, timestampMs: 8 },
      { type: "pointer_move", pointerId: 1, x: 160, y: 124, timestampMs: 32 },
      { type: "pointer_up", pointerId: 1, x: 160, y: 124, timestampMs: 54 },
    ],
    expected: {
      stage: "Dragging",
      sealStatus: "intent-registered",
      completed: false,
      engagedFaultCount: 1,
      totalProgressMin: 0.12,
      requiredEventNames: [
        "slide:01:entered",
      ],
    },
  },
];

export const SLIDE01_TIMER_GUARD_MODULES = [
  "components/slides/slide01-ui/routeb/DiagnosticRitual.tsx",
  "components/slides/slide01-ui/routeb/DiagnosticRail.tsx",
  "components/slides/slide01-ui/routeb/FaultCardsSurface.tsx",
  "components/slides/slide01-ui/routeb/RightSeal.tsx",
  "components/slides/slide01-ui/routeb/useDiagnosticRitual.ts",
  "components/slides/slide01-ui/routeb/slide01.helpers.ts",
  "components/slides/slide01-ui/routeb/slide01.replay.ts",
  "components/slides/slide01-ui/routeb/slide01.fixtures.ts",
] as const;

export function getSlide01FixtureById(id: string): Slide01ReplayFixture | undefined {
  return SLIDE01_GESTURE_TRACE_FIXTURES.find((fixture) => fixture.id === id);
}

export function selectSlide01FixturesByExpectation(
  status: Slide01ReplayFixture["expected"]["sealStatus"]
): Slide01ReplayFixture[] {
  return SLIDE01_GESTURE_TRACE_FIXTURES.filter(
    (fixture) => fixture.expected.sealStatus === status
  );
}
