import { GuideScript } from '../types';

export const enterpriseGuideScript: GuideScript = {
  id: 'enterprise',
  title: 'Enterprise Guided Demo',
  description: 'Deterministic evidence-first guided demo for executive presentations.',
  meta: {
    version: '2.0.0',
    owner: 'wow/tour/guide/scripts/enterprise.ts',
    audience: 'investor-room',
    durationMin: 15,
    tags: ['evidence-first', 'enterprise', 'deterministic'],
  },
  steps: [
    {
      id: 's00-context',
      title: 'Step 1 - Frame the decision lens',
      body: 'Anchor the room on evidence-first operations. Clarify that the demo proves operational trust under audit pressure.',
      footnote: 'Keep this concise. We are establishing decision criteria before features.',
      nextTease: 'Next, move directly into compliance proof.',
      directorNotes: [
        'State this line: We do not start with promises, we start with inspectable evidence.',
        'Pause for one beat after context line to let the framing land.',
      ],
      action: { type: 'state', text: 'Keep opening slide visible and deliver the thesis sentence.' },
      successText: 'Thesis framed and baseline context established.',
      successLabel: 'Decision lens set',
      targetSelector: '[data-testid="deck-root"]',
      missingTargetWarning: 'Deck root unavailable. Continue verbally.',
      spotlightPadding: 14,
      spotlightRadius: 20,
      pulseTarget: true,
      connector: true,
      placement: 'center',
      fallbackAllowNext: true,
      allowNextBeforeComplete: true,
      evidence: [
        {
          id: 'deck-mounted',
          label: 'Deck root is mounted',
          hint: 'The deck host must exist before running guided controls.',
          source: { type: 'selector', selector: '[data-testid="deck-root"]', mode: 'exists' },
        },
        {
          id: 'slide-00-visible',
          label: 'Opening slide is active',
          hint: 'Audience should see slide 00 context before moving to proof.',
          source: { type: 'slide', slide: 0 },
        },
      ],
      completion: {
        type: 'all',
        rules: [
          { type: 'evidence', evidenceId: 'deck-mounted' },
          { type: 'evidence', evidenceId: 'slide-00-visible' },
        ],
      },
    },
    {
      id: 's04-navigation',
      title: 'Step 2 - Move to compliance proof',
      body: 'Navigate to Slide04 where traceability and immutable evidence are inspectable by design.',
      nextTease: 'Once in proof view, lock the TRACEABLE evidence token.',
      directorNotes: [
        'Narration line: trust is earned where controls are inspectable, not where claims are loud.',
      ],
      action: { type: 'navigate', text: 'Use deck navigation to reach Slide04.' },
      successText: 'Proof surface is visible.',
      successLabel: 'Proof surface live',
      targetSelector: '.deck-stage-frame',
      missingTargetWarning: 'Slide frame unavailable. Continue manually.',
      spotlightPadding: 8,
      spotlightRadius: 18,
      connector: true,
      placement: 'top',
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'slide-04-visible',
          label: 'Slide04 active',
          hint: 'The compliance slide must be active before evidence actions.',
          source: { type: 'slide', slide: 4 },
        },
        {
          id: 'proof-host-mounted',
          label: 'Proof host mounted',
          hint: 'The deck stage frame is required for target focus.',
          source: { type: 'selector', selector: '.deck-stage-frame', mode: 'exists' },
        },
      ],
      completion: {
        type: 'all',
        rules: [
          { type: 'evidence', evidenceId: 'slide-04-visible' },
          { type: 'evidence', evidenceId: 'proof-host-mounted' },
        ],
      },
    },
    {
      id: 's04-lock-trace',
      title: 'Step 3 - Lock TRACEABLE evidence',
      body: 'Activate TRACEABLE to capture immutable evidence in context.',
      footnote: 'This is the first hard evidence event in the flow.',
      nextTease: 'Now export proof so legal and ops can share it.',
      directorNotes: [
        'Narration line: one click transforms narrative confidence into inspectable artifact.',
      ],
      action: { type: 'click', selector: '[data-badge="TRACEABLE"]' },
      successText: 'Trace lock event captured.',
      successLabel: 'Trace locked',
      targetSelector: '[data-badge="TRACEABLE"]',
      missingTargetWarning: 'TRACEABLE badge not found.',
      spotlightPadding: 10,
      spotlightRadius: 14,
      pulseTarget: true,
      connector: true,
      placement: 'right',
      evidence: [
        {
          id: 'traceable-mounted',
          label: 'TRACEABLE control mounted',
          hint: 'The badge must exist before interaction.',
          source: { type: 'selector', selector: '[data-badge="TRACEABLE"]', mode: 'exists' },
        },
        {
          id: 'trace-lock-event',
          label: 'Evidence lock event captured',
          hint: 'Click TRACEABLE once and confirm lock event.',
          source: { type: 'event', name: 'evidence:locked', count: 1 },
        },
      ],
      completion: {
        type: 'all',
        rules: [
          { type: 'evidence', evidenceId: 'traceable-mounted' },
          { type: 'evidence', evidenceId: 'trace-lock-event' },
        ],
      },
    },
    {
      id: 's04-copy-token',
      title: 'Step 4 - Export audit token',
      body: 'Copy the audit token so proof can travel across compliance, legal, and operations.',
      nextTease: 'Then open AI lane with deterministic fixture flow.',
      directorNotes: [
        'Narration line: portability is the difference between a demo and an operational system.',
      ],
      action: { type: 'click', selector: '[data-testid="s04-copy-token"]' },
      successText: 'Audit token copied event captured.',
      successLabel: 'Token exported',
      targetSelector: '[data-testid="s04-copy-token"]',
      missingTargetWarning: 'Copy token button missing.',
      spotlightPadding: 10,
      spotlightRadius: 12,
      pulseTarget: true,
      connector: true,
      placement: 'right',
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'copy-token-mounted',
          label: 'Copy token control mounted',
          hint: 'Copy action requires token button to be visible.',
          source: { type: 'selector', selector: '[data-testid="s04-copy-token"]', mode: 'exists' },
        },
        {
          id: 'token-copy-event',
          label: 'Token copied',
          hint: 'Click Copy and confirm evidence:copied event.',
          source: { type: 'event', name: 'evidence:copied', count: 1 },
        },
      ],
      completion: {
        type: 'all',
        rules: [
          { type: 'evidence', evidenceId: 'token-copy-event' },
          { type: 'any', rules: [{ type: 'evidence', evidenceId: 'copy-token-mounted' }, { type: 'slide', slide: 4 }] },
        ],
      },
    },
    {
      id: 'open-chat',
      title: 'Step 5 - Open AI lane',
      body: 'Open AIChat to translate proof-language into board-language without improvisation.',
      nextTease: 'Load deterministic fixture next.',
      directorNotes: ['Narration line: we standardize first response quality, then scale interaction.'],
      action: { type: 'click', selector: '[data-testid="chat-toggle"]' },
      successText: 'AI panel opened.',
      successLabel: 'AI lane open',
      targetSelector: '[data-testid="chat-toggle"]',
      missingTargetWarning: 'Chat toggle not mounted.',
      spotlightPadding: 10,
      spotlightRadius: 16,
      pulseTarget: true,
      connector: true,
      placement: 'left',
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'chat-toggle-mounted',
          label: 'Chat toggle mounted',
          hint: 'The chat toggle should be visible on stage.',
          source: { type: 'selector', selector: '[data-testid="chat-toggle"]', mode: 'exists' },
        },
        {
          id: 'chat-open-event',
          label: 'AI opened event',
          hint: 'Open chat and capture ai:opened event.',
          source: { type: 'event', name: 'ai:opened', count: 1 },
        },
      ],
      completion: {
        type: 'all',
        rules: [
          { type: 'evidence', evidenceId: 'chat-open-event' },
          { type: 'evidence', evidenceId: 'chat-toggle-mounted' },
        ],
      },
    },
    {
      id: 'fixture-load',
      title: 'Step 6 - Load deterministic fixture',
      body: 'Load fixture to guarantee repeatable response quality in demos and rehearsals.',
      footnote: 'Determinism is a demo quality control.',
      nextTease: 'Inject guided compliance question and send.',
      directorNotes: ['Narration line: same prompt, same evidence quality, every rehearsal.'],
      action: { type: 'click', selector: '[data-testid="chat-load-fixture"]' },
      successText: 'Fixture loaded event captured.',
      successLabel: 'Fixture loaded',
      targetSelector: '[data-testid="chat-load-fixture"]',
      missingTargetWarning: 'Fixture load button unavailable.',
      spotlightPadding: 10,
      spotlightRadius: 12,
      pulseTarget: true,
      connector: true,
      placement: 'left',
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'fixture-button-mounted',
          label: 'Fixture button mounted',
          hint: 'Load fixture control must exist before clicking.',
          source: { type: 'selector', selector: '[data-testid="chat-load-fixture"]', mode: 'exists' },
        },
        {
          id: 'fixture-event',
          label: 'Fixture loaded event',
          hint: 'Capture ai:fixture-loaded after clicking.',
          source: { type: 'event', name: 'ai:fixture-loaded', count: 1 },
        },
      ],
      completion: {
        type: 'any',
        rules: [
          { type: 'evidence', evidenceId: 'fixture-event' },
          {
            type: 'all',
            rules: [
              { type: 'evidence', evidenceId: 'fixture-button-mounted' },
              { type: 'event', name: 'ai:response', count: 1 },
            ],
          },
        ],
      },
    },
    {
      id: 'ask-guided-question',
      title: 'Step 7 - Ask compliance question',
      body: 'Use guided wording and send the question from chat input.',
      readAloudText: 'What evidence appears first under audit pressure and how quickly can operations surface it?',
      nextTease: 'Move to modular operating surface next.',
      directorNotes: [
        'Read the sentence exactly as shown.',
        'Pause after send to let response quality prove consistency.',
      ],
      action: { type: 'chat', text: 'Paste guided question and click send.' },
      successText: 'Guided question sent event captured.',
      successLabel: 'Question sent',
      targetSelector: '[data-testid="chat-input"]',
      missingTargetWarning: 'Chat input missing.',
      spotlightPadding: 10,
      spotlightRadius: 12,
      pulseTarget: true,
      connector: true,
      placement: 'left',
      fallbackAllowNext: true,
      pasteQuestion: 'Given this deck, what evidence appears first under audit pressure and why?',
      evidence: [
        {
          id: 'chat-input-mounted',
          label: 'Chat input mounted',
          hint: 'Input must be available to send guided question.',
          source: { type: 'selector', selector: '[data-testid="chat-input"]', mode: 'exists' },
        },
        {
          id: 'question-sent-event',
          label: 'Question sent event',
          hint: 'Send question and capture ai:sent.',
          source: { type: 'event', name: 'ai:sent', count: 1 },
        },
      ],
      completion: {
        type: 'all',
        rules: [
          { type: 'evidence', evidenceId: 'question-sent-event' },
          { type: 'any', rules: [{ type: 'evidence', evidenceId: 'chat-input-mounted' }, { type: 'event', name: 'ai:response', count: 1 }] },
        ],
      },
    },
    {
      id: 'slide05-transition',
      title: 'Step 8 - Transition to Slide05 capability surface',
      body: 'Move to Slide05 and show operational know-how modules as evidence anchors.',
      nextTease: 'Capture module interaction evidence on Slide05.',
      directorNotes: ['Narration line: capability proof appears as interaction-ready modules, not static bullet claims.'],
      action: { type: 'navigate', text: 'Navigate to Slide05.' },
      successText: 'Slide05 active and guide surface ready.',
      successLabel: 'Slide05 live',
      targetSelector: '[data-tour-id="slide05-surface"]',
      missingTargetWarning: 'Slide05 guide surface missing.',
      spotlightPadding: 10,
      spotlightRadius: 16,
      connector: true,
      placement: 'top',
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'slide05-visible',
          label: 'Slide05 active',
          hint: 'Navigate to slide index 5.',
          source: { type: 'slide', slide: 5 },
        },
        {
          id: 'slide05-surface-mounted',
          label: 'Slide05 surface mounted',
          hint: 'Surface anchor should exist for guide targeting.',
          source: { type: 'selector', selector: '[data-tour-id="slide05-surface"]', mode: 'exists' },
        },
      ],
      completion: {
        type: 'all',
        rules: [{ type: 'evidence', evidenceId: 'slide05-visible' }, { type: 'evidence', evidenceId: 'slide05-surface-mounted' }],
      },
    },
    {
      id: 'slide05-module-proof',
      title: 'Step 9 - Capture Slide05 module evidence',
      body: 'Hover or click modules to prove interaction-ready operational evidence.',
      nextTease: 'Move to Slide12 module internals next.',
      directorNotes: ['Narration line: each module interaction emits evidence; this is demonstrable behavior, not script theater.'],
      action: { type: 'click', selector: '[data-tour-id="slide05-module-03"]' },
      successText: 'Slide05 module interaction evidence captured.',
      successLabel: 'Module proof captured',
      targetSelector: '[data-tour-id^="slide05-module-"]',
      missingTargetWarning: 'Slide05 modules not mounted.',
      spotlightPadding: 10,
      spotlightRadius: 14,
      pulseTarget: true,
      connector: true,
      placement: 'right',
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'module-hovered',
          label: 'Slide05 module hovered',
          hint: 'Hover any Slide05 module to emit evidence event.',
          source: { type: 'event', name: 'slide05:module-hover', count: 1 },
        },
        {
          id: 'module-clicked',
          label: 'Slide05 module clicked',
          hint: 'Click one module to emit click evidence event.',
          source: { type: 'event', name: 'slide05:module-click', count: 1 },
        },
      ],
      completion: {
        type: 'any',
        rules: [{ type: 'evidence', evidenceId: 'module-hovered' }, { type: 'evidence', evidenceId: 'module-clicked' }],
      },
    },
    {
      id: 's12-transition',
      title: 'Step 10 - Move to Slide12 module internals',
      body: 'Navigate to Slide12 to show software-like module behavior.',
      nextTease: 'Open ConditionScore for inspectable KPI internals.',
      directorNotes: ['Narration line: this is where product mechanics become visibly inspectable.'],
      action: { type: 'navigate', text: 'Navigate to Slide12.' },
      successText: 'Slide12 active.',
      successLabel: 'Module stage ready',
      targetSelector: '.deck-stage-frame',
      missingTargetWarning: 'Slide frame missing.',
      spotlightPadding: 8,
      spotlightRadius: 16,
      connector: true,
      placement: 'top',
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'slide12-visible',
          label: 'Slide12 active',
          hint: 'Navigate to slide index 12.',
          source: { type: 'slide', slide: 11 },
        },
      ],
      completion: { type: 'evidence', evidenceId: 'slide12-visible' },
    },
    {
      id: 's12-open-module',
      title: 'Step 11 - Open ConditionScore module',
      body: 'Open ConditionScore and show KPI confidence coming from structured internals.',
      nextTease: 'Finish in case reveal with deployable commitment.',
      directorNotes: ['Narration line: KPI confidence is generated in-system, not added in a report.'],
      action: { type: 'click', selector: '[data-s12-module="conditionscore"]' },
      successText: 'ConditionScore module open event captured.',
      successLabel: 'ConditionScore open',
      targetSelector: '[data-s12-module="conditionscore"]',
      missingTargetWarning: 'ConditionScore card unavailable.',
      spotlightPadding: 10,
      spotlightRadius: 14,
      pulseTarget: true,
      connector: true,
      placement: 'right',
      evidence: [
        {
          id: 'module-card-mounted',
          label: 'ConditionScore card mounted',
          hint: 'Card must be visible before opening.',
          source: { type: 'selector', selector: '[data-s12-module="conditionscore"]', mode: 'exists' },
        },
        {
          id: 'module-open-event',
          label: 'ConditionScore opened event',
          hint: 'Capture module:opened with key=conditionscore.',
          source: { type: 'event', name: 'module:opened', count: 1, where: { key: 'conditionscore' } },
        },
      ],
      completion: {
        type: 'all',
        rules: [{ type: 'evidence', evidenceId: 'module-open-event' }, { type: 'evidence', evidenceId: 'module-card-mounted' }],
      },
    },
    {
      id: 's17-case-reveal',
      title: 'Step 12 - Case reveal and deployment close',
      body: 'Move to Slide17, open evidence, then commit KPI CTA for deployment confidence.',
      footnote: 'End with a concrete 30/60 day commitment.',
      directorNotes: [
        'Narration line: evidence first, KPI second, deployment third.',
        'Close with explicit next action and owner.',
      ],
      action: { type: 'open', text: 'On Slide17 click Abrir evidencia then Deployable in 30 days CTA.' },
      successText: 'Case evidence and KPI commitment both captured.',
      successLabel: 'Deployment commitment',
      targetSelector: '[data-testid="s17-open-evidence"]',
      missingTargetWarning: 'Case reveal controls unavailable.',
      spotlightPadding: 10,
      spotlightRadius: 14,
      pulseTarget: true,
      connector: true,
      placement: 'right',
      fallbackAllowNext: true,
      allowNextBeforeComplete: true,
      evidence: [
        {
          id: 'slide17-visible',
          label: 'Slide17 active',
          hint: 'Navigate to final case reveal slide.',
          source: { type: 'slide', slide: 17 },
        },
        {
          id: 'case-open-event',
          label: 'Case evidence opened',
          hint: 'Click evidence open control.',
          source: { type: 'event', name: 'case:evidence-opened', count: 1 },
        },
        {
          id: 'case-kpi-event',
          label: 'KPI commitment captured',
          hint: 'Click KPI CTA to capture commitment event.',
          source: { type: 'event', name: 'case:kpi-committed', count: 1 },
        },
      ],
      completion: {
        type: 'all',
        rules: [
          { type: 'evidence', evidenceId: 'slide17-visible' },
          { type: 'evidence', evidenceId: 'case-open-event' },
          { type: 'evidence', evidenceId: 'case-kpi-event' },
        ],
      },
    },
  ],
};

