import { GuideScript } from '../types';

export const guidedDemoScript: GuideScript = {
  id: 'guided-demo',
  title: 'Interactive Guided Demo',
  description: 'Operator-assisted evidence-first guided script with deterministic completion and presenter cues.',
  meta: {
    version: '2.0.0',
    owner: 'wow/tour/guide/scripts/guided-demo.ts',
    audience: 'operator-and-presenter',
    durationMin: 18,
    tags: ['interactive', 'operator', 'evidence-first', 'deterministic'],
  },
  steps: [
    {
      id: 'g00-readiness',
      title: 'Readiness gate - verify stage and root',
      body: 'Before speaking, verify that the deck root and stage frame are mounted. This ensures targets and evidence anchors are available.',
      footnote: 'This is a hard readiness gate to avoid dead demos.',
      nextTease: 'Then set context on slide 00 in one sentence.',
      directorNotes: [
        'Do not start narration if readiness evidence is missing.',
        'If target missing, call out fallback and continue with manual control.',
      ],
      action: { type: 'state', text: 'Verify stage mount indicators in operator panel.' },
      successText: 'Runtime readiness confirmed.',
      successLabel: 'Runtime ready',
      targetSelector: '[data-testid="deck-root"]',
      missingTargetWarning: 'Deck root missing. Reload before live audience if possible.',
      spotlightPadding: 10,
      spotlightRadius: 18,
      placement: 'center',
      pulseTarget: true,
      connector: true,
      fallbackAllowNext: true,
      allowNextBeforeComplete: true,
      evidence: [
        {
          id: 'g00-deck-root',
          label: 'Deck root exists',
          hint: 'Root container is required for every guide anchor.',
          source: { type: 'selector', selector: '[data-testid="deck-root"]', mode: 'exists' },
        },
        {
          id: 'g00-stage-frame',
          label: 'Stage frame exists',
          hint: 'Stage frame should be mounted for spotlight targeting.',
          source: { type: 'selector', selector: '.deck-stage-frame', mode: 'exists' },
        },
      ],
      completion: {
        type: 'all',
        rules: [{ type: 'evidence', evidenceId: 'g00-deck-root' }, { type: 'evidence', evidenceId: 'g00-stage-frame' }],
      },
    },
    {
      id: 'g01-context-slide00',
      title: 'Context gate - opening narrative',
      body: 'Stay on slide 00 and frame the system as a trust-production engine. Avoid feature lists at this point.',
      nextTease: 'Move to Slide04 to expose compliance evidence controls.',
      directorNotes: [
        'Say: We produce trust with real-time evidence, not retrospective reports.',
        'Keep this under 20 seconds.',
      ],
      action: { type: 'state', text: 'Deliver thesis while opening slide remains active.' },
      successText: 'Opening context delivered on correct slide.',
      successLabel: 'Context delivered',
      targetSelector: '[data-testid="deck-root"]',
      spotlightPadding: 12,
      spotlightRadius: 20,
      placement: 'center',
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'g01-slide00',
          label: 'Slide00 active',
          hint: 'Audience should see opening context.',
          source: { type: 'slide', slide: 0 },
        },
        {
          id: 'g01-slide-changed',
          label: 'Slide change evidence emitted',
          hint: 'slide:changed event should be present for deterministic timeline.',
          source: { type: 'event', name: 'slide:changed', count: 1, where: { to: 0 } },
        },
      ],
      completion: {
        type: 'any',
        rules: [{ type: 'evidence', evidenceId: 'g01-slide00' }, { type: 'evidence', evidenceId: 'g01-slide-changed' }],
      },
    },
    {
      id: 'g02-nav-slide04',
      title: 'Navigation gate - move to compliance layer',
      body: 'Navigate to Slide04 where evidence locking and tokenization can be proven with direct actions.',
      nextTease: 'Lock TRACEABLE evidence once Slide04 is active.',
      directorNotes: [
        'Narration: this is where auditable trust becomes inspectable.',
        'Do not discuss AI yet; stay in compliance proof lane.',
      ],
      action: { type: 'navigate', text: 'Use navigation controls to reach Slide04.' },
      successText: 'Slide04 reached and proof controls in view.',
      successLabel: 'Proof stage reached',
      targetSelector: '.deck-stage-frame',
      placement: 'top',
      spotlightPadding: 8,
      spotlightRadius: 16,
      connector: true,
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'g02-slide04',
          label: 'Slide04 active',
          hint: 'Proof narrative begins on slide index 4.',
          source: { type: 'slide', slide: 4 },
        },
        {
          id: 'g02-stage-frame',
          label: 'Stage frame still mounted',
          hint: 'Stage frame should persist during navigation.',
          source: { type: 'selector', selector: '.deck-stage-frame', mode: 'exists' },
        },
      ],
      completion: {
        type: 'all',
        rules: [{ type: 'evidence', evidenceId: 'g02-slide04' }, { type: 'evidence', evidenceId: 'g02-stage-frame' }],
      },
    },
    {
      id: 'g03-lock-evidence',
      title: 'Evidence gate - lock TRACEABLE control',
      body: 'Click TRACEABLE badge to emit immutable lock evidence.',
      nextTease: 'Copy the token to prove evidence portability.',
      directorNotes: [
        'Narration: this click is the compliance spine.',
        'Show confidence only after event is captured.',
      ],
      action: { type: 'click', selector: '[data-badge="TRACEABLE"]' },
      successText: 'Evidence lock event captured.',
      successLabel: 'Lock captured',
      targetSelector: '[data-badge="TRACEABLE"]',
      missingTargetWarning: 'TRACEABLE badge missing from Slide04.',
      placement: 'right',
      spotlightPadding: 10,
      spotlightRadius: 14,
      pulseTarget: true,
      connector: true,
      evidence: [
        {
          id: 'g03-traceable-selector',
          label: 'TRACEABLE control present',
          hint: 'Badge must exist before click.',
          source: { type: 'selector', selector: '[data-badge="TRACEABLE"]', mode: 'exists' },
        },
        {
          id: 'g03-lock-event',
          label: 'evidence:locked event',
          hint: 'A single lock event should be captured.',
          source: { type: 'event', name: 'evidence:locked', count: 1 },
        },
      ],
      completion: {
        type: 'all',
        rules: [{ type: 'evidence', evidenceId: 'g03-traceable-selector' }, { type: 'evidence', evidenceId: 'g03-lock-event' }],
      },
    },
    {
      id: 'g04-copy-evidence-token',
      title: 'Portability gate - copy audit token',
      body: 'Copy the token to prove evidence can move between legal, operations, and board reporting.',
      nextTease: 'Open AI lane after token proof is captured.',
      directorNotes: [
        'Narration: portability turns control evidence into organizational coordination.',
      ],
      action: { type: 'click', selector: '[data-testid="s04-copy-token"]' },
      successText: 'Token copy event captured.',
      successLabel: 'Token portable',
      targetSelector: '[data-testid="s04-copy-token"]',
      missingTargetWarning: 'Token copy button missing.',
      placement: 'right',
      spotlightPadding: 10,
      spotlightRadius: 14,
      pulseTarget: true,
      connector: true,
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'g04-token-button',
          label: 'Token button present',
          hint: 'Copy button must be mounted.',
          source: { type: 'selector', selector: '[data-testid="s04-copy-token"]', mode: 'exists' },
        },
        {
          id: 'g04-token-event',
          label: 'evidence:copied event',
          hint: 'Copy should emit evidence:copied.',
          source: { type: 'event', name: 'evidence:copied', count: 1 },
        },
      ],
      completion: {
        type: 'all',
        rules: [{ type: 'evidence', evidenceId: 'g04-token-event' }, { type: 'any', rules: [{ type: 'evidence', evidenceId: 'g04-token-button' }, { type: 'slide', slide: 4 }] }],
      },
    },
    {
      id: 'g05-open-chat',
      title: 'Interface gate - open AI chat',
      body: 'Open AI chat interface to convert evidence into executive language.',
      nextTease: 'Load fixture to keep response deterministic.',
      directorNotes: ['Narration: AI is used as translation assist, not source of truth.'],
      action: { type: 'click', selector: '[data-testid="chat-toggle"]' },
      successText: 'AI chat opened event captured.',
      successLabel: 'AI interface opened',
      targetSelector: '[data-testid="chat-toggle"]',
      missingTargetWarning: 'Chat toggle unavailable.',
      placement: 'left',
      spotlightPadding: 10,
      spotlightRadius: 14,
      pulseTarget: true,
      connector: true,
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'g05-chat-toggle',
          label: 'Chat toggle present',
          hint: 'Chat toggle must exist.',
          source: { type: 'selector', selector: '[data-testid="chat-toggle"]', mode: 'exists' },
        },
        {
          id: 'g05-chat-open',
          label: 'ai:opened event',
          hint: 'Opening chat must emit ai:opened event.',
          source: { type: 'event', name: 'ai:opened', count: 1 },
        },
      ],
      completion: {
        type: 'all',
        rules: [{ type: 'evidence', evidenceId: 'g05-chat-toggle' }, { type: 'evidence', evidenceId: 'g05-chat-open' }],
      },
    },
    {
      id: 'g06-load-fixture',
      title: 'Determinism gate - load fixture',
      body: 'Load deterministic fixture response before asking custom prompts.',
      nextTease: 'Inject guided audit question next.',
      directorNotes: [
        'Narration: we lock first-response quality with deterministic fixtures.',
        'If fixture unavailable, explain fallback and continue.',
      ],
      action: { type: 'click', selector: '[data-testid="chat-load-fixture"]' },
      successText: 'Fixture loaded and response event captured.',
      successLabel: 'Fixture deterministic path ready',
      targetSelector: '[data-testid="chat-load-fixture"]',
      missingTargetWarning: 'Fixture button unavailable.',
      placement: 'left',
      spotlightPadding: 10,
      spotlightRadius: 12,
      pulseTarget: true,
      connector: true,
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'g06-fixture-button',
          label: 'Fixture control mounted',
          hint: 'Button should be visible while chat open.',
          source: { type: 'selector', selector: '[data-testid="chat-load-fixture"]', mode: 'exists' },
        },
        {
          id: 'g06-fixture-event',
          label: 'ai:fixture-loaded event',
          hint: 'Fixture load should emit ai:fixture-loaded.',
          source: { type: 'event', name: 'ai:fixture-loaded', count: 1 },
        },
      ],
      completion: {
        type: 'any',
        rules: [
          { type: 'evidence', evidenceId: 'g06-fixture-event' },
          { type: 'all', rules: [{ type: 'evidence', evidenceId: 'g06-fixture-button' }, { type: 'event', name: 'ai:response', count: 1 }] },
        ],
      },
    },
    {
      id: 'g07-ask-audit-question',
      title: 'Question gate - send guided audit prompt',
      body: 'Use the guided question and send it from input to keep framing consistent across demos.',
      readAloudText: 'What evidence appears first under audit pressure and what is the expected time-to-proof?',
      nextTease: 'Transition to Slide05 capability wall.',
      directorNotes: [
        'Paste question exactly and send once.',
        'After response appears, tie answer back to token lock event.',
      ],
      action: { type: 'chat', text: 'Paste guided question and click Send.' },
      successText: 'Question send event captured.',
      successLabel: 'Question sent',
      targetSelector: '[data-testid="chat-input"]',
      missingTargetWarning: 'Chat input missing.',
      placement: 'left',
      spotlightPadding: 10,
      spotlightRadius: 12,
      pulseTarget: true,
      connector: true,
      fallbackAllowNext: true,
      pasteQuestion: 'Given this operation, what evidence appears first under audit pressure and how is it verified?',
      evidence: [
        {
          id: 'g07-chat-input',
          label: 'Chat input present',
          hint: 'Input must be available for guided prompt.',
          source: { type: 'selector', selector: '[data-testid="chat-input"]', mode: 'exists' },
        },
        {
          id: 'g07-sent-event',
          label: 'ai:sent event',
          hint: 'Sending guided prompt must emit ai:sent.',
          source: { type: 'event', name: 'ai:sent', count: 1 },
        },
      ],
      completion: {
        type: 'all',
        rules: [{ type: 'evidence', evidenceId: 'g07-sent-event' }, { type: 'any', rules: [{ type: 'evidence', evidenceId: 'g07-chat-input' }, { type: 'event', name: 'ai:response', count: 1 }] }],
      },
    },
    {
      id: 'g08-nav-slide05',
      title: 'Capability gate - navigate to Slide05',
      body: 'Move to Slide05 and prepare for module-level evidence interactions.',
      nextTease: 'Capture module hover/click evidence.',
      directorNotes: [
        'Narration: this slide connects industrial experience with live operational modules.',
      ],
      action: { type: 'navigate', text: 'Navigate to Slide05.' },
      successText: 'Slide05 and guide anchors visible.',
      successLabel: 'Slide05 anchor live',
      targetSelector: '[data-tour-id="slide05-surface"]',
      missingTargetWarning: 'Slide05 surface anchor missing.',
      placement: 'top',
      spotlightPadding: 10,
      spotlightRadius: 16,
      connector: true,
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'g08-slide05',
          label: 'Slide05 active',
          hint: 'Slide index should be 5.',
          source: { type: 'slide', slide: 5 },
        },
        {
          id: 'g08-surface-anchor',
          label: 'Slide05 surface anchor exists',
          hint: 'Guide should detect slide05 surface element.',
          source: { type: 'selector', selector: '[data-tour-id="slide05-surface"]', mode: 'exists' },
        },
        {
          id: 'g08-module-grid-anchor',
          label: 'Module grid anchor exists',
          hint: 'Guide should detect modules container for evidence focus.',
          source: { type: 'selector', selector: '[data-tour-id="slide05-modules"]', mode: 'exists' },
        },
      ],
      completion: {
        type: 'all',
        rules: [
          { type: 'evidence', evidenceId: 'g08-slide05' },
          { type: 'evidence', evidenceId: 'g08-surface-anchor' },
          { type: 'evidence', evidenceId: 'g08-module-grid-anchor' },
        ],
      },
    },
    {
      id: 'g09-slide05-hover',
      title: 'Interaction gate - capture module hover',
      body: 'Hover any Slide05 module to emit evidence event and show interactivity is not scripted timing.',
      nextTease: 'Capture module click as stronger evidence.',
      directorNotes: [
        'Narration: operator action emits deterministic evidence event.',
      ],
      action: { type: 'state', text: 'Hover any module card on Slide05.' },
      successText: 'Slide05 hover evidence captured.',
      successLabel: 'Hover evidence',
      targetSelector: '[data-tour-id^="slide05-module-"]',
      missingTargetWarning: 'Slide05 modules unavailable.',
      placement: 'right',
      spotlightPadding: 10,
      spotlightRadius: 14,
      pulseTarget: true,
      connector: true,
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'g09-hover-event',
          label: 'slide05:module-hover event',
          hint: 'Hovering module should emit hover event at least once.',
          source: { type: 'event', name: 'slide05:module-hover', count: 1 },
        },
      ],
      completion: { type: 'evidence', evidenceId: 'g09-hover-event' },
    },
    {
      id: 'g10-slide05-click',
      title: 'Interaction gate - capture module click',
      body: 'Click a Slide05 module to emit click evidence and complete module interaction proof.',
      nextTease: 'Transition to Slide12 for module internals.',
      directorNotes: [
        'Narration: every operator action generates verifiable state transition.',
      ],
      action: { type: 'click', selector: '[data-tour-id="slide05-module-03"]' },
      successText: 'Slide05 click evidence captured.',
      successLabel: 'Click evidence',
      targetSelector: '[data-tour-id="slide05-module-03"]',
      missingTargetWarning: 'Specific module target unavailable, click any module.',
      placement: 'right',
      spotlightPadding: 10,
      spotlightRadius: 14,
      pulseTarget: true,
      connector: true,
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'g10-click-event',
          label: 'slide05:module-click event',
          hint: 'Click should emit module click event.',
          source: { type: 'event', name: 'slide05:module-click', count: 1 },
        },
        {
          id: 'g10-focus-event',
          label: 'slide05:module-focus event',
          hint: 'Focus event is optional but desirable for keyboard path.',
          required: false,
          source: { type: 'event', name: 'slide05:module-focus', count: 1 },
        },
      ],
      completion: { type: 'evidence', evidenceId: 'g10-click-event' },
    },
    {
      id: 'g11-nav-slide12',
      title: 'Navigation gate - move to Slide12',
      body: 'Navigate to Slide12 and prepare to open ConditionScore module internals.',
      nextTease: 'Open ConditionScore and observe module event.',
      directorNotes: [
        'Narration: from capability claims to inspectable module internals.',
      ],
      action: { type: 'navigate', text: 'Navigate to Slide12.' },
      successText: 'Slide12 active and ready.',
      successLabel: 'Slide12 ready',
      targetSelector: '.deck-stage-frame',
      placement: 'top',
      spotlightPadding: 8,
      spotlightRadius: 16,
      connector: true,
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'g11-slide12',
          label: 'Slide12 active',
          hint: 'Move to index 12.',
          source: { type: 'slide', slide: 11 },
        },
      ],
      completion: { type: 'evidence', evidenceId: 'g11-slide12' },
    },
    {
      id: 'g12-open-conditionscore',
      title: 'Module gate - open ConditionScore',
      body: 'Open ConditionScore module and confirm module:opened event with expected key.',
      nextTease: 'Move to Slide17 final case proof.',
      directorNotes: [
        'Narration: this event proves module-level behavior.',
      ],
      action: { type: 'click', selector: '[data-s12-module="conditionscore"]' },
      successText: 'ConditionScore open event captured.',
      successLabel: 'ConditionScore opened',
      targetSelector: '[data-s12-module="conditionscore"]',
      missingTargetWarning: 'ConditionScore card missing.',
      placement: 'right',
      spotlightPadding: 10,
      spotlightRadius: 14,
      pulseTarget: true,
      connector: true,
      evidence: [
        {
          id: 'g12-module-card',
          label: 'ConditionScore card present',
          hint: 'Card must be mounted.',
          source: { type: 'selector', selector: '[data-s12-module="conditionscore"]', mode: 'exists' },
        },
        {
          id: 'g12-module-event',
          label: 'module:opened with key conditionscore',
          hint: 'Open card and capture event.',
          source: { type: 'event', name: 'module:opened', count: 1, where: { key: 'conditionscore' } },
        },
      ],
      completion: {
        type: 'all',
        rules: [{ type: 'evidence', evidenceId: 'g12-module-card' }, { type: 'evidence', evidenceId: 'g12-module-event' }],
      },
    },
    {
      id: 'g13-nav-slide17',
      title: 'Navigation gate - move to Slide17 case reveal',
      body: 'Navigate to Slide17 where final evidence and deployment CTA are closed.',
      nextTease: 'Open case evidence next.',
      directorNotes: [
        'Narration: final segment demonstrates evidence-to-action closure.',
      ],
      action: { type: 'navigate', text: 'Navigate to Slide17.' },
      successText: 'Slide17 active.',
      successLabel: 'Finale slide active',
      targetSelector: '[data-testid="s17-open-evidence"]',
      missingTargetWarning: 'Case reveal button missing.',
      placement: 'top',
      spotlightPadding: 10,
      spotlightRadius: 16,
      connector: true,
      fallbackAllowNext: true,
      evidence: [
        {
          id: 'g13-slide17',
          label: 'Slide17 active',
          hint: 'Move to final slide index 17.',
          source: { type: 'slide', slide: 17 },
        },
      ],
      completion: { type: 'evidence', evidenceId: 'g13-slide17' },
    },
    {
      id: 'g14-open-case-evidence',
      title: 'Closure gate - open final evidence',
      body: 'Click Abrir evidencia and confirm event emission.',
      nextTease: 'Finish with KPI commitment CTA.',
      directorNotes: [
        'Narration: show evidence first before commitment language.',
      ],
      action: { type: 'click', selector: '[data-testid="s17-open-evidence"]' },
      successText: 'Case evidence open event captured.',
      successLabel: 'Final evidence opened',
      targetSelector: '[data-testid="s17-open-evidence"]',
      missingTargetWarning: 'Evidence button missing.',
      placement: 'right',
      spotlightPadding: 10,
      spotlightRadius: 14,
      pulseTarget: true,
      connector: true,
      evidence: [
        {
          id: 'g14-case-open-event',
          label: 'case:evidence-opened event',
          hint: 'Click evidence button once.',
          source: { type: 'event', name: 'case:evidence-opened', count: 1 },
        },
      ],
      completion: { type: 'evidence', evidenceId: 'g14-case-open-event' },
    },
    {
      id: 'g15-kpi-commit',
      title: 'Closure gate - commit deployable KPI',
      body: 'Click final CTA and close with 30/60 day KPI commitment.',
      footnote: 'Offer restart for full guided loop replay if requested.',
      directorNotes: [
        'Narration: deployment confidence comes from proven evidence path, not slide polish.',
        'Close with owner + next review date.',
      ],
      action: { type: 'click', selector: '[data-testid="s17-kpi-cta"]' },
      successText: 'KPI commitment event captured.',
      successLabel: 'Commitment complete',
      targetSelector: '[data-testid="s17-kpi-cta"]',
      missingTargetWarning: 'KPI CTA missing; close verbally with explicit commitment.',
      placement: 'left',
      spotlightPadding: 10,
      spotlightRadius: 14,
      pulseTarget: true,
      connector: true,
      fallbackAllowNext: true,
      allowNextBeforeComplete: true,
      evidence: [
        {
          id: 'g15-kpi-event',
          label: 'case:kpi-committed event',
          hint: 'Click CTA to emit KPI commitment event.',
          source: { type: 'event', name: 'case:kpi-committed', count: 1 },
        },
      ],
      completion: { type: 'evidence', evidenceId: 'g15-kpi-event' },
    },
  ],
};

