import { TourScript } from '../types';

export const enterpriseTourScript: TourScript = {
  id: 'enterprise',
  title: 'Enterprise Compliance Demo',
  description: 'Deterministic evidence-first tour with click-only controls for investor and compliance demos.',
  steps: [
    {
      id: 's00-start',
      title: 'Evidence-First Opening',
      body: 'This deck demonstrates evidence-first operations. Start by anchoring the narrative on Slide00.',
      action: { type: 'state', text: 'Stay on Slide00 and frame the thesis in one sentence.' },
      successText: 'Slide00 is active.',
      targetSelector: '[data-testid="deck-root"]',
      placement: 'center',
      spotlightPadding: 12,
      spotlightRadius: 20,
      completion: { type: 'slide', slide: 0 },
      fallbackAllowNext: true,
      missingTargetWarning: 'Deck root was not found. Continue manually.',
      allowNextBeforeComplete: true,
      pulseTarget: true,
      connector: true,
    },
    {
      id: 's04-nav',
      title: 'Navigate to Proof Layer',
      body: 'Move to Slide04 to enter compliance-grade traceability mode.',
      action: { type: 'navigate', text: 'Use existing slide navigation to reach Slide04.' },
      successText: 'Slide04 is active.',
      targetSelector: '.deck-stage-frame',
      placement: 'top',
      spotlightPadding: 8,
      spotlightRadius: 18,
      completion: { type: 'slide', slide: 4 },
      fallbackAllowNext: true,
      missingTargetWarning: 'Slide container target missing.',
      connector: true,
    },
    {
      id: 's04-lock-evidence',
      title: 'Lock Evidence',
      body: 'Click the TRACEABLE badge to lock a defensible proof statement.',
      action: { type: 'click', selector: '[data-badge="TRACEABLE"]' },
      successText: 'Evidence badge lock event captured.',
      targetSelector: '[data-badge="TRACEABLE"]',
      placement: 'right',
      spotlightPadding: 10,
      spotlightRadius: 14,
      completion: { type: 'event', name: 'evidence:locked', count: 1 },
      missingTargetWarning: 'TRACEABLE badge not mounted.',
      pulseTarget: true,
      connector: true,
    },
    {
      id: 's04-copy-token',
      title: 'Copy Compliance Token',
      body: 'Copy the evidence token to show handoff-ready traceability.',
      action: { type: 'click', selector: '[data-testid="s04-copy-token"]' },
      successText: 'Evidence token copied event captured.',
      targetSelector: '[data-testid="s04-copy-token"]',
      placement: 'right',
      spotlightPadding: 10,
      spotlightRadius: 12,
      completion: { type: 'event', name: 'evidence:copied', count: 1 },
      missingTargetWarning: 'Copy token button missing.',
      pulseTarget: true,
      connector: true,
    },
    {
      id: 'open-aichat',
      title: 'Open AI Investor Chat',
      body: 'Open AIChat to translate operational signals into investor language.',
      action: { type: 'click', selector: '[data-testid="chat-toggle"]' },
      successText: 'AI chat window is visible.',
      targetSelector: '[data-testid="chat-toggle"]',
      placement: 'left',
      spotlightPadding: 10,
      spotlightRadius: 18,
      completion: { type: 'event', name: 'ai:opened', count: 1 },
      missingTargetWarning: 'Chat toggle is missing.',
      pulseTarget: true,
      connector: true,
    },
    {
      id: 'fixture-load',
      title: 'Load Deterministic Fixture',
      body: 'Use WOW fixture mode so the demo remains deterministic and offline-safe.',
      action: { type: 'click', selector: '[data-testid="chat-load-fixture"]' },
      successText: 'Fixture response was injected into chat.',
      targetSelector: '[data-testid="chat-load-fixture"]',
      placement: 'left',
      spotlightPadding: 10,
      spotlightRadius: 12,
      completion: { type: 'event', name: 'ai:fixture-loaded', count: 1 },
      missingTargetWarning: 'Load Fixture control missing. Continue with Paste question.',
      fallbackAllowNext: true,
      pulseTarget: true,
      connector: true,
    },
    {
      id: 'ask-killer-question',
      title: 'Ask the Killer Question',
      body: 'Paste the guided question and send it to keep wording consistent across demos.',
      action: { type: 'chat', text: 'Use Ask This and send the prompt.' },
      successText: 'AI sent event captured.',
      targetSelector: '[data-testid="chat-input"]',
      placement: 'left',
      spotlightPadding: 10,
      spotlightRadius: 12,
      completion: { type: 'event', name: 'ai:sent', count: 1 },
      pasteQuestion: 'Given this deck, what evidence appears first under audit pressure and why?',
      missingTargetWarning: 'Chat input not available.',
      fallbackAllowNext: true,
      pulseTarget: true,
      connector: true,
    },
    {
      id: 's12-modules',
      title: 'Navigate to Core Modules',
      body: 'Go to Slide12 to show this behaves like software, not a static deck.',
      action: { type: 'navigate', text: 'Use existing nav controls to reach Slide12.' },
      successText: 'Slide12 is active.',
      targetSelector: '.deck-stage-frame',
      placement: 'top',
      spotlightPadding: 8,
      spotlightRadius: 18,
      completion: { type: 'slide', slide: 12 },
      missingTargetWarning: 'Slide container missing.',
      fallbackAllowNext: true,
      connector: true,
    },
    {
      id: 's12-open-card',
      title: 'Open One Module',
      body: 'Open the ConditionScore module and highlight detail chips and signal behavior.',
      action: { type: 'click', selector: '[data-s12-module="conditionscore"]' },
      successText: 'Module open event captured.',
      targetSelector: '[data-s12-module="conditionscore"]',
      placement: 'right',
      spotlightPadding: 10,
      spotlightRadius: 14,
      completion: { type: 'event', name: 'module:opened', where: { key: 'conditionscore' }, count: 1 },
      missingTargetWarning: 'ConditionScore card missing.',
      pulseTarget: true,
      connector: true,
    },
    {
      id: 's17-case-reveal',
      title: 'Case Reveal + Evidence Modal',
      body: 'Move to Slide17 and open the evidence modal to close with proof before narrative.',
      action: { type: 'open', text: 'Navigate to Slide17 and click Abrir evidencia.' },
      successText: 'Evidence modal opened on case slide.',
      targetSelector: '[data-testid="s17-open-evidence"]',
      placement: 'right',
      spotlightPadding: 10,
      spotlightRadius: 14,
      completion: {
        type: 'all',
        rules: [
          { type: 'slide', slide: 17 },
          { type: 'event', name: 'case:evidence-opened', count: 1 },
        ],
      },
      missingTargetWarning: 'Case reveal trigger missing.',
      fallbackAllowNext: true,
      pulseTarget: true,
      connector: true,
    },
    {
      id: 'close-kpi',
      title: 'Close with KPI Commitment',
      body: 'Close the demo with 30/60-day KPI language tied to measurable risk reduction.',
      action: { type: 'state', text: 'State the KPI commitment and next operating checkpoint.' },
      successText: 'Tour completion reached.',
      targetSelector: '.wow-case-reveal-shell',
      placement: 'center',
      spotlightPadding: 12,
      spotlightRadius: 20,
      completion: { type: 'manual' },
      allowNextBeforeComplete: true,
      fallbackAllowNext: true,
      missingTargetWarning: 'Case shell not found; close verbally.',
      connector: true,
    },
  ],
};
