import { TourScript } from '../types';

export const enterpriseTourScript: TourScript = {
  id: 'enterprise',
  title: 'Enterprise Investor Demo',
  description: 'Deterministic guided flow for investors with evidence-first narration.',
  steps: [
    {
      id: 's00-context',
      title: 'Set Investment Context',
      instruction: 'On Slide00, anchor the thesis: evidence-first operations over retrospective reporting.',
      targetSelector: '.deck-stage-frame',
      placement: 'center',
      completion: { type: 'slide', slide: 0 },
      allowNextBeforeComplete: true,
    },
    {
      id: 's04-badge-hover',
      title: 'Reveal Defensibility',
      instruction: 'Go to Slide04 and hover an evidence badge to surface proof language.',
      targetSelector: '[data-badge="REAL_TIME"]',
      placement: 'right',
      completion: { type: 'event', name: 'evidence:hover', count: 1 },
    },
    {
      id: 's04-badge-lock',
      title: 'Lock Evidence Statement',
      instruction: 'Click a badge to lock the tooltip and show deterministic traceability.',
      targetSelector: '[data-badge="TRACEABLE"]',
      placement: 'right',
      completion: { type: 'event', name: 'evidence:locked', count: 1 },
    },
    {
      id: 's04-copy-token',
      title: 'Copy Evidence Token',
      instruction: 'Use COPY to demonstrate operational proof handoff readiness.',
      targetSelector: '.a11y-focus',
      placement: 'bottom',
      completion: { type: 'event', name: 'evidence:copied', count: 1 },
    },
    {
      id: 'ai-question-1',
      title: 'Ask First Investor Question',
      instruction: 'Open AIChat, paste the guided question, and send it.',
      targetSelector: '[data-testid="chat-input"]',
      placement: 'left',
      completion: { type: 'event', name: 'ai:sent', count: 1 },
      pasteQuestion: 'Given this deck, what evidence appears first under audit pressure and why?',
    },
    {
      id: 'ai-response-1',
      title: 'Wait for AI Response',
      instruction: 'Let the first response resolve before continuing.',
      targetSelector: '[data-testid="chat-window"]',
      placement: 'left',
      completion: { type: 'event', name: 'ai:response', count: 1 },
    },
    {
      id: 's12-open-module',
      title: 'Open Core Module',
      instruction: 'Move to Slide12 and open one CORE module card.',
      targetSelector: '[data-s12-module="conditionscore"]',
      placement: 'right',
      completion: { type: 'event', name: 'module:opened', count: 1 },
    },
    {
      id: 's12-hover-module',
      title: 'Show Module Signal',
      instruction: 'Hover another module card to show signal behavior.',
      targetSelector: '[data-s12-module="healthradar"]',
      placement: 'right',
      completion: { type: 'event', name: 'module:hover', count: 1 },
    },
    {
      id: 'ai-question-2',
      title: 'Ask KPI Commitment Question',
      instruction: 'Paste the second question in AIChat and send it.',
      targetSelector: '[data-testid="chat-input"]',
      placement: 'left',
      completion: { type: 'event', name: 'ai:sent', count: 2 },
      pasteQuestion: 'What 60-day KPI would prove this system reduced operational risk in measurable terms?',
    },
    {
      id: 'wrap-slide17',
      title: 'Close with Case Reveal',
      instruction: 'Navigate to Slide17 and close with measurable business impact from the case.',
      targetSelector: '.wow-case-reveal-shell',
      placement: 'center',
      completion: {
        type: 'any',
        rules: [
          { type: 'slide', slide: 17 },
          { type: 'event', name: 'slide:changed', where: { to: 17 }, count: 1 },
        ],
      },
      allowNextBeforeComplete: true,
    },
  ],
};
