import { TourScript } from '../types';

export const enterpriseTourScript: TourScript = {
  id: 'enterprise',
  title: 'Enterprise Guided Demo',
  description: 'A deterministic investor walkthrough: evidence first, outcomes second, commitment last.',
  steps: [
    {
      id: 's00-start',
      title: 'Step 1 - Anchor the operating thesis',
      body: 'Start on the opening frame. Position the product as evidence-first operations, not retrospective reporting.',
      footnote: 'The audience should hear operational trust before feature depth.',
      nextTease: 'Next, we lock proof in the compliance layer.',
      directorNotes: ['Say this now: We lead with evidence, not claims.', 'Pause here: let the opening settle for one beat.'],
      action: { type: 'state', text: 'Keep Slide00 visible and frame the thesis in one sentence.' },
      successText: 'Opening context is established.',
      successLabel: 'Context locked',
      targetSelector: '[data-testid="deck-root"]',
      placement: 'center',
      spotlightPadding: 14,
      spotlightRadius: 24,
      completion: { type: 'slide', slide: 0 },
      fallbackAllowNext: true,
      missingTargetWarning: 'Deck root was not found. Continue manually.',
      allowNextBeforeComplete: true,
      pulseTarget: true,
      connector: true,
    },
    {
      id: 's04-nav',
      title: 'Step 2 - Move to compliance proof',
      body: 'Navigate to Slide04. This is where compliance-grade traceability becomes visible in one action.',
      nextTease: 'We will lock immutable evidence on the next click.',
      directorNotes: ['Say this now: This is where trust becomes inspectable.'],
      action: { type: 'navigate', text: 'Use existing deck navigation to reach Slide04.' },
      successText: 'Proof slide is active.',
      successLabel: 'Proof layer reached',
      targetSelector: '.deck-stage-frame',
      placement: 'top',
      spotlightPadding: 10,
      spotlightRadius: 18,
      completion: { type: 'slide', slide: 4 },
      fallbackAllowNext: true,
      missingTargetWarning: 'Slide container target missing.',
      connector: true,
    },
    {
      id: 's04-lock-evidence',
      title: 'Step 3 - Lock evidence for traceability',
      body: 'Select the TRACEABLE badge. This action creates an immutable audit reference in the narrative.',
      footnote: 'One click should feel enterprise-safe and defensible.',
      nextTease: 'Now export the token that legal and operations can share.',
      directorNotes: ['Say this now: This lock is the compliance spine.'],
      action: { type: 'click', selector: '[data-badge="TRACEABLE"]' },
      successText: 'Evidence lock event captured.',
      successLabel: 'Evidence locked',
      targetSelector: '[data-badge="TRACEABLE"]',
      placement: 'right',
      spotlightPadding: 10,
      spotlightRadius: 14,
      completion: { type: 'event', name: 'evidence:locked', count: 1 },
      missingTargetWarning: 'TRACEABLE badge not mounted.',
      pulseTarget: true,
      connector: true,
    },
    {
      id: 's04-copy-token',
      title: 'Step 4 - Export the audit token',
      body: 'Click Copy to capture a portable proof token for cross-functional handoff.',
      nextTease: 'Next, we move from proof to AI-assisted board language.',
      directorNotes: ['Pause here: let them register that proof is transferable.'],
      action: { type: 'click', selector: '[data-testid="s04-copy-token"]' },
      successText: 'Token copy event captured.',
      successLabel: 'Trace committed',
      targetSelector: '[data-testid="s04-copy-token"]',
      placement: 'right',
      spotlightPadding: 10,
      spotlightRadius: 12,
      completion: { type: 'event', name: 'evidence:copied', count: 1 },
      missingTargetWarning: 'Copy token button missing.',
      pulseTarget: true,
      connector: true,
    },
    {
      id: 'open-aichat',
      title: 'Step 5 - Open investor AI lane',
      body: 'Open AIChat. The tour preps a deterministic question that converts operations into executive language.',
      nextTease: 'Load the deterministic fixture to keep this demo reproducible.',
      directorNotes: ['Say this now: We never improvise the first answer in a boardroom.'],
      action: { type: 'click', selector: '[data-testid="chat-toggle"]' },
      successText: 'AI chat opened.',
      successLabel: 'AI lane ready',
      targetSelector: '[data-testid="chat-toggle"]',
      placement: 'left',
      spotlightPadding: 10,
      spotlightRadius: 18,
      completion: { type: 'event', name: 'ai:opened', count: 1 },
      missingTargetWarning: 'Chat toggle is missing.',
      pulseTarget: true,
      connector: true,
    },
    {
      id: 'fixture-load',
      title: 'Step 6 - Load deterministic investor fixture',
      body: 'Press Load Fixture to demonstrate deterministic, network-safe response quality.',
      footnote: 'No random prompts during critical demos.',
      nextTease: 'Then ask the core compliance question with guided wording.',
      directorNotes: ['Say this now: Determinism protects demo quality under pressure.'],
      action: { type: 'click', selector: '[data-testid="chat-load-fixture"]' },
      successText: 'Fixture response injected.',
      successLabel: 'Fixture loaded',
      targetSelector: '[data-testid="chat-load-fixture"]',
      placement: 'left',
      spotlightPadding: 10,
      spotlightRadius: 12,
      completion: { type: 'event', name: 'ai:fixture-loaded', count: 1 },
      missingTargetWarning: 'Load Fixture control missing. Continue with Ask this now.',
      fallbackAllowNext: true,
      pulseTarget: true,
      connector: true,
    },
    {
      id: 'ask-killer-question',
      title: 'Step 7 - Ask the compliance question',
      body: 'Inject the guided question and send it. Keep wording exact for repeatable executive impact.',
      readAloudText: 'The first evidence an auditor asks for is captured at the moment of risk, not reconstructed later.',
      nextTease: 'Next we show the core modules behaving as software, not slides.',
      directorNotes: ['Read this line aloud from the highlight.', 'Pause after send: let the answer breathe.'],
      action: { type: 'chat', text: 'Use Ask this now, then click Send.' },
      successText: 'Question sent from guided prompt.',
      successLabel: 'Question launched',
      targetSelector: '[data-testid="chat-input"]',
      placement: 'left',
      spotlightPadding: 10,
      spotlightRadius: 12,
      completion: { type: 'event', name: 'ai:sent', count: 1 },
      pasteQuestion: 'Given this deck, what evidence appears first under audit pressure and why?',
      missingTargetWarning: 'Chat input not available.',
      fallbackAllowNext: true,
      pulseTarget: true,
      connector: true,
    },
    {
      id: 's12-modules',
      title: 'Step 8 - Transition to operating modules',
      body: 'Move to Slide12 to prove this system behaves like real software modules under load.',
      nextTease: 'Open a module to reveal internal signal behavior.',
      directorNotes: ['Say this now: This is operational software, not deck theater.'],
      action: { type: 'navigate', text: 'Use existing navigation to reach Slide12.' },
      successText: 'Slide12 active.',
      successLabel: 'Module stage ready',
      targetSelector: '.deck-stage-frame',
      placement: 'top',
      spotlightPadding: 8,
      spotlightRadius: 18,
      completion: { type: 'slide', slide: 12 },
      missingTargetWarning: 'Slide container missing.',
      fallbackAllowNext: true,
      connector: true,
    },
    {
      id: 's12-open-card',
      title: 'Step 9 - Reveal ConditionScore internals',
      body: 'Open the ConditionScore card. Highlight chips and signal bars as live product behavior.',
      nextTease: 'Finale next: evidence-first case reveal and deployment CTA.',
      directorNotes: ['Say this now: KPI confidence is produced here, not added later.'],
      action: { type: 'click', selector: '[data-s12-module="conditionscore"]' },
      successText: 'Module open event captured.',
      successLabel: 'KPI module opened',
      targetSelector: '[data-s12-module="conditionscore"]',
      placement: 'right',
      spotlightPadding: 10,
      spotlightRadius: 14,
      completion: { type: 'event', name: 'module:opened', where: { key: 'conditionscore' }, count: 1 },
      missingTargetWarning: 'ConditionScore card missing.',
      pulseTarget: true,
      connector: true,
    },
    {
      id: 's17-case-reveal',
      title: 'Step 10 - Evidence-first finale',
      body: 'Move to Slide17 and open evidence first. Then show KPI commitment as an executive close.',
      nextTease: 'Close with 30-day deploy plan and restart option.',
      directorNotes: ['Say this now: Evidence first, KPI second, deployment third.'],
      action: { type: 'open', text: 'Go to Slide17 and click Abrir evidencia.' },
      successText: 'Case evidence opened and finale reached.',
      successLabel: 'Finale unlocked',
      targetSelector: '[data-testid="s17-open-evidence"]',
      placement: 'right',
      spotlightPadding: 10,
      spotlightRadius: 14,
      completion: {
        type: 'all',
        rules: [
          { type: 'slide', slide: 17 },
          { type: 'event', name: 'case:evidence-opened', count: 1 },
        ],
      },
      missingTargetWarning: 'Case reveal trigger missing.',
      fallbackAllowNext: true,
      pulseTarget: true,
      connector: true,
    },
    {
      id: 'close-kpi',
      title: 'Step 11 - Commit to deployment',
      body: 'Use the Deployable in 30 days CTA, then close with a concrete 30/60-day KPI commitment.',
      footnote: 'End with execution confidence, not abstract potential.',
      directorNotes: ['Let them ask questions after this line.', 'Offer restart if they want the full loop again.'],
      action: { type: 'click', selector: '[data-testid="s17-kpi-cta"]' },
      successText: 'CTA acknowledged and close complete.',
      successLabel: 'KPI captured',
      targetSelector: '[data-testid="s17-kpi-cta"]',
      placement: 'left',
      spotlightPadding: 10,
      spotlightRadius: 14,
      completion: { type: 'event', name: 'case:kpi-committed', count: 1 },
      allowNextBeforeComplete: true,
      fallbackAllowNext: true,
      missingTargetWarning: 'Final CTA not found; close verbally.',
      pulseTarget: true,
      connector: true,
    },
  ],
};
